// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV2wrYcZKbThPprJNXUHxf0qqRCyaB-YM',
    appId: '1:1063314638875:web:2c97b6e750e1fbe82510be',
    messagingSenderId: '1063314638875',
    projectId: 'vehiclerentalapp-8a8ab',
    authDomain: 'vehiclerentalapp-8a8ab.firebaseapp.com',
    storageBucket: 'vehiclerentalapp-8a8ab.firebasestorage.app',
    measurementId: 'G-B3F4SVF4Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Zqr_90P1STktaCom9bEK7pRCIfvm3os',
    appId: '1:1063314638875:android:ff2a0fdce6d4aa2a2510be',
    messagingSenderId: '1063314638875',
    projectId: 'vehiclerentalapp-8a8ab',
    storageBucket: 'vehiclerentalapp-8a8ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPcr6VQjTgoZ8DPSOM-vsF7w6xAqXQsZs',
    appId: '1:1063314638875:ios:f27f564099cb58062510be',
    messagingSenderId: '1063314638875',
    projectId: 'vehiclerentalapp-8a8ab',
    storageBucket: 'vehiclerentalapp-8a8ab.firebasestorage.app',
    androidClientId: '1063314638875-epo9uvl0k68rf14glpv6u0jimlub0lk9.apps.googleusercontent.com',
    iosClientId: '1063314638875-lke4gbbk7i1enfhvf0n51ufat0rql25o.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicalrentalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPcr6VQjTgoZ8DPSOM-vsF7w6xAqXQsZs',
    appId: '1:1063314638875:ios:f27f564099cb58062510be',
    messagingSenderId: '1063314638875',
    projectId: 'vehiclerentalapp-8a8ab',
    storageBucket: 'vehiclerentalapp-8a8ab.firebasestorage.app',
    androidClientId: '1063314638875-epo9uvl0k68rf14glpv6u0jimlub0lk9.apps.googleusercontent.com',
    iosClientId: '1063314638875-lke4gbbk7i1enfhvf0n51ufat0rql25o.apps.googleusercontent.com',
    iosBundleId: 'com.example.vehicalrentalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV2wrYcZKbThPprJNXUHxf0qqRCyaB-YM',
    appId: '1:1063314638875:web:3f073d7223cc2e882510be',
    messagingSenderId: '1063314638875',
    projectId: 'vehiclerentalapp-8a8ab',
    authDomain: 'vehiclerentalapp-8a8ab.firebaseapp.com',
    storageBucket: 'vehiclerentalapp-8a8ab.firebasestorage.app',
    measurementId: 'G-LR4CEDJ91N',
  );
}
